services:
  # Backend Service
  - type: web
    name: dental-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: dental-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

  # Frontend Service as Web Service
  - type: web
    name: dental-ai-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s build -p $PORT
    envVars:
      - key: REACT_APP_API_URL
        value: https://dental-ai-backend.onrender.com

# Database
databases:
  - name: dental-db
    databaseName: dental_production
    user: dental_user 